# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 535)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 496, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.calendar = QtWidgets.QCalendarWidget(parent=self.verticalLayoutWidget)
        self.calendar.setObjectName("calendar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.calendar)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.days = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.days.setObjectName("days")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.days)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.typeofroom = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.typeofroom.setObjectName("typeofroom")
        self.typeofroom.addItem("")
        self.typeofroom.addItem("")
        self.typeofroom.addItem("")
        self.typeofroom.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.typeofroom)
        self.description = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.description.setText("")
        self.description.setScaledContents(True)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.description)
        self.verticalLayout.addLayout(self.formLayout)
        self.rezerwacja = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.rezerwacja.setObjectName("rezerwacja")
        self.verticalLayout.addWidget(self.rezerwacja)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Rezerwacja pokoju hotelowego"))
        self.label_2.setText(_translate("Dialog", "Data Rezerwacji"))
        self.label_3.setText(_translate("Dialog", "Liczba dni"))
        self.label_4.setText(_translate("Dialog", "typ pokoju"))
        self.typeofroom.setItemText(0, _translate("Dialog", "Ekologiczny"))
        self.typeofroom.setItemText(1, _translate("Dialog", "Harry Potter"))
        self.typeofroom.setItemText(2, _translate("Dialog", "Krolewski"))
        self.typeofroom.setItemText(3, _translate("Dialog", "Programistyczny"))
        self.rezerwacja.setText(_translate("Dialog", "Rezerwuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
